In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn 

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error

In [ ]:
'''
Készíts egy függvényt, betölti majd vissza adja az iris adathalmazt.


Egy példa a kimenetre: iris
return type: sklearn.utils.Bunch
függvény neve: load_iris_data
'''

In [5]:
def load_iris_data() -> sklearn.utils.Bunch: 
    return load_iris()

load_iris_data()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
'''
Készíts egy függvényt, ami a betölti az virágokhoz tartozó levél méretket egy dataframebe, majd az első 5 sort visszaadja.
Minden oszlop tartalmazza, hogy az milyen mérethez tartozik.

Egy példa a bemenetre: iris
Egy példa a kimenetre: iris_df
return type: pandas.core.frame.DataFrame
függvény neve: check_data
'''

In [13]:
def check_data(iris) -> pd.core.frame.DataFrame:
    iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
    return iris_df.head(5)

check_data(load_iris_data())

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
''' 
Készíts egy függvényt ami előkészíti az adatokat egy lineaáris regressziós model feltanításához.
Featurejeink legyenek a levél méretek kivéve a "sepal length (cm)", ez legyen a targetünk.

Egy példa a bemenetre: iris
Egy példa a kimenetre: X, y
return type: (numpy.ndarray, numpy.ndarray)
függvény neve: linear_train_data
'''

In [28]:
def linear_train_data(iris) -> (np.ndarray, np.ndarray):
    iris_database = iris
    X = np.array(iris_database.data[:,1:4])
    y = np.array(iris_database.data[:,0])
    return (X,y)

linear_train_data(load_iris_data())

(array([[3.5, 1.4, 0.2],
        [3. , 1.4, 0.2],
        [3.2, 1.3, 0.2],
        [3.1, 1.5, 0.2],
        [3.6, 1.4, 0.2],
        [3.9, 1.7, 0.4],
        [3.4, 1.4, 0.3],
        [3.4, 1.5, 0.2],
        [2.9, 1.4, 0.2],
        [3.1, 1.5, 0.1],
        [3.7, 1.5, 0.2],
        [3.4, 1.6, 0.2],
        [3. , 1.4, 0.1],
        [3. , 1.1, 0.1],
        [4. , 1.2, 0.2],
        [4.4, 1.5, 0.4],
        [3.9, 1.3, 0.4],
        [3.5, 1.4, 0.3],
        [3.8, 1.7, 0.3],
        [3.8, 1.5, 0.3],
        [3.4, 1.7, 0.2],
        [3.7, 1.5, 0.4],
        [3.6, 1. , 0.2],
        [3.3, 1.7, 0.5],
        [3.4, 1.9, 0.2],
        [3. , 1.6, 0.2],
        [3.4, 1.6, 0.4],
        [3.5, 1.5, 0.2],
        [3.4, 1.4, 0.2],
        [3.2, 1.6, 0.2],
        [3.1, 1.6, 0.2],
        [3.4, 1.5, 0.4],
        [4.1, 1.5, 0.1],
        [4.2, 1.4, 0.2],
        [3.1, 1.5, 0.2],
        [3.2, 1.2, 0.2],
        [3.5, 1.3, 0.2],
        [3.6, 1.4, 0.1],
        [3. , 1.3, 0.2],
        [3.4, 1.5, 0.2],


In [ ]:
''' 
Készíts egy függvényt ami előkészíti az adatokat egy logisztikus regressziós model feltanításához.
Featurejeink legyenek a levél méretek, targetünk pedig a 0, 1-es virág osztályok.
Fontos csak azokkal az adatokkal tanítsunk amihez tartozik adott target. 

Egy példa a bemenetre: iris
Egy példa a kimenetre: X, y
return type: (numpy.ndarray, numpy.ndarray)
függvény neve: logistic_train_data
'''

In [29]:
def logistic_train_data(iris) -> (np.ndarray, np.ndarray):
    iris_database = iris
    mask = np.where((iris_database.target == 0) | (iris_database.target == 1))
    X = np.array(iris_database.data[mask])
    y = np.array(iris_database.target[mask])
    return (X,y)

logistic_train_data(load_iris_data())

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [ ]:
'''
Készíts egy függvényt ami feldarabolja az adatainkat train és test részre. Az adatok 20%-át használjuk fel a teszteléshez.
Tegyük determenisztikussá a darabolást, ennek értéke legyen 42.

Egy példa a bemenetre: X, y
Egy példa a kimenetre: X_train, X_test, y_train, y_test
return type: (numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)
függvény neve: split_data
'''

In [40]:
def split_data(X, y) -> (np.ndarray, np.ndarray, np.ndarray, np.ndarray):
    return train_test_split(X, y, test_size=0.2, random_state=42)

X, y = linear_train_data(load_iris_data())
X_train, X_test, y_train, y_test = split_data(X, y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(120, 3) (30, 3) (120,) (30,)


In [ ]:
'''
Készíts egy függvényt ami feltanít egy lineaáris regressziós modelt, majd visszatér vele.

Egy példa a bemenetre: X_train, y_train
Egy példa a kimenetre: model
return type: sklearn.linear_model._base.LinearRegression
függvény neve: train_linear_regression
'''

In [42]:
def train_linear_regression(X_train, y_train) -> LinearRegression:
    model = LinearRegression()
    model.fit(X_train, y_train)
    return model

X, y = linear_train_data(load_iris_data())
X_train, X_test, y_train, y_test = split_data(X, y)
train_linear_regression(X_train, y_train)

LinearRegression()

In [ ]:
'''
Készíts egy függvényt ami feltanít egy logisztikus regressziós modelt, majd visszatér vele.

Egy példa a bemenetre: X_train, y_train
Egy példa a kimenetre: model
return type: sklearn.linear_model._base.LogisticRegression
függvény neve: train_logistic_regression
'''

In [45]:
def train_logistic_regression(X_train, y_train) -> LogisticRegression: #error with "sklearn.linear_model._base.LogisticRegression"
    model = LogisticRegression()
    model.fit(X_train, y_train)
    return model

X, y = logistic_train_data(load_iris_data())
X_train, X_test, y_train, y_test = split_data(X, y)
train_linear_regression(X_train, y_train)

LinearRegression()

In [ ]:
''' 
Készíts egy függvényt, ami a feltanított modellel predikciót tud végre hajtani.

Egy példa a bemenetre: model, X_test
Egy példa a kimenetre: y_pred
return type: numpy.ndarray
függvény neve: predict
'''

In [46]:
def predict(model , X_test) -> np.ndarray:
    return model.predict(X_test)

X, y = logistic_train_data(load_iris_data())
X_train, X_test, y_train, y_test = split_data(X, y)
predict(train_linear_regression(X_train, y_train), X_test)

array([ 1.27061255,  1.03303088,  1.19204473,  0.09472387,  0.0877796 ,
        0.00803349, -0.10992901,  0.91326231, -0.05224692, -0.02911943,
       -0.00732381,  0.08913421,  1.04364718, -0.15849115,  1.03641661,
       -0.04169119,  1.09993684,  1.20536608,  0.03292854,  0.05854626])

In [ ]:
'''
Készíts egy függvényt, ami vizualizálni tudja a label és a predikciók közötti eltérést.
Használj scatter plotot a diagram elkészítéséhez.

Diagram címe legyen: 'Actual vs Predicted Target Values'
Az x tengely címe legyen: 'Actual'
Az y tengely címe legyen: 'Predicted'

Egy példa a bemenetre: y_test, y_pred
Egy példa a kimenetre: scatter plot
return type: matplotlib.figure.Figure
függvény neve: plot_actual_vs_predicted
'''

In [ ]:
''' 
Készíts egy függvényt, ami a Négyzetes hiba (MSE) értékét számolja ki a predikciók és a valós értékek között.

Egy példa a bemenetre: y_test, y_pred
Egy példa a kimenetre: mse
return type: float
függvény neve: evaluate_model
'''